### ISSUE TITLE
Code styles 

### ISSUE THREAD

**Issue by hamidafghan** [shakib98/Homework#2]
@shakib98  Try to style your code in web.php file.

**Comment by shakib98** [comment]
Thanks, I have done code style to web.php file

**Comment by hamidafghan** [comment]
@shakib98 please separate  the  each routes with an empty line. Try to observe these roles [URL Nameing](https://www.palantir.net/blog/palantirnets-guide-digital-governance-url-naming-conventions)

**Comment by shakib98** [comment]
Thanks, i have modified the routes file and i created an empty line for each of my routes
